export let CANVAS_WIDTH = 600;
export let CANVAS_HEIGHT = 600;
export const SET_CANVAS_WIDTH = (w:number) => CANVAS_WIDTH = w;
export const SET_CANVAS_HEIGHT = (h:number) => CANVAS_HEIGHT = h;
export const PIPE_DISTANCE = 300;
const GRAVITY_PX_PER_S_SQUARED = 2000;
const GRAVITY_CONVERSION_FACTOR = 1/1_000_000;
export const GRAVITY_PX_PER_MS_SQUARED = GRAVITY_PX_PER_S_SQUARED*GRAVITY_CONVERSION_FACTOR;